### ISSUE TITLE
Update to 5.3

### ISSUE THREAD

**Issue by samas92i** [guillermomartinez/filemanager-laravel#37]
Hello,

Can tou update for laravel 5.3 ?

**Comment by clytras** [comment]
Please update `composer.json` to support laravel 5.3

**Comment by guillermomartinez** [comment]
Support laravel 5.3 https://github.com/guillermomartinez/filemanager-laravel/commit/561e7094ec73a283775abb57ddc64a5724ddfbd1

**Comment by clytras** [comment]
Thanks.

Although now composer can install this, it won't work with laravel 5.3 because the `Route::controller` method does not exists anymore, it's deprecated. See upgrade guide at "Deprecations":

[https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0](https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0)

> Implicit controller routes using Route::controller have been deprecated. Please use explicit route registration in your routes file. This will likely be extracted into a package.

I have the filemanager working by registering the routes like this:

```
Route::group(['middleware' => 'auth'], function(){
    Route::get('filemanager/show', 'FilemanagerLaravelController@getShow');
    Route::get('filemanager/connectors', 'FilemanagerLaravelController@getConnectors');
    Route::post('filemanager/connectors', 'FilemanagerLaravelController@postConnectors');*/
});
```
